### ISSUE TITLE
这个有必要吗？开启NFC的情况下耗电吗？

### ISSUE THREAD

**Issue by Lovefish** [Xposed-Modules-Repo/com.gswxxn.autonfc#2]
好奇。如果耗电的话我也关掉。

**Comment by GSWXXN** [comment]
NFC 耗电量微乎其微, 可以忽略不计

**Comment by Lovefish** [comment]
> NFC 耗电量微乎其微, 可以忽略不计

所以，这个插件有什么用。。。

**Comment by GSWXXN** [comment]
> 所以，这个插件有什么用。。。

之前我用华为的时候系统是自带这个功能的, 换回小米没这个功能我就不爽, 虽然这个功能没什么大用. 再一个对于我自己写个小模块玩玩, 可以练练手. 前一段时间小米在状态栏加了 NFC 的指示图标, 我认为如果 NFC 一直保持一个状态这个图标是没有意义的, 而我也不想简单粗暴的把这个图标移除, 这个模块也是给这个指示图标有相对较大的意义

以上是我开发并使用这个模块的原因, 对于大部分的使用者可能就是觉得平时关闭 NFC 在关键时刻自动打开可能会省一点电 ~(虽然 NFC 本身就不是特别耗电~
